export default {
  'Roboto-Light': require('./Roboto/Roboto-Light.ttf'),
  'Roboto-LightItalic': require('./Roboto/Roboto-LightItalic.ttf'),
  'Roboto-Regular': require('./Roboto/Roboto-Medium.ttf'),
  'Roboto-Italic': require('./Roboto/Roboto-MediumItalic.ttf'),
  'Roboto-Medium': require('./Roboto/Roboto-Medium.ttf'),
  'Roboto-MediumItalic': require('./Roboto/Roboto-MediumItalic.ttf'),
  'Roboto-Bold': require('./Roboto/Roboto-Bold.ttf'),
  'Roboto-BoldItalic': require('./Roboto/Roboto-BoldItalic.ttf'),
  'Roboto-Black': require('./Roboto/Roboto-Black.ttf'),
  'Roboto-BlackItalic': require('./Roboto/Roboto-BlackItalic.ttf'),

  'Montserrat-Light': require('./Montserrat/Montserrat-Light.ttf'),
  'Montserrat-LightItalic': require('./Montserrat/Montserrat-LightItalic.ttf'),
  'Montserrat-Black': require('./Montserrat/Montserrat-Black.ttf'),
  'Montserrat-BlackItalic': require('./Montserrat/Montserrat-BlackItalic.ttf'),
  'Montserrat-Bold': require('./Montserrat/Montserrat-Bold.ttf'),
  'Montserrat-BoldItalic': require('./Montserrat/Montserrat-BoldItalic.ttf'),
  'Montserrat-Regular': require('./Montserrat/Montserrat-Medium.ttf'),
  'Montserrat-Italic': require('./Montserrat/Montserrat-MediumItalic.ttf'),
  'Montserrat-Medium': require('./Montserrat/Montserrat-Medium.ttf'),
  'Montserrat-MediumItalic': require('./Montserrat/Montserrat-MediumItalic.ttf'),
  'Montserrat-SemiBold': require('./Montserrat/Montserrat-SemiBold.ttf'),
  'Montserrat-SemiBoldItalic': require('./Montserrat/Montserrat-SemiBoldItalic.ttf'),

  "FugazOne-Regular": require('./FugazOne-Regular.ttf'),
  "Lemon-Regular": require('./Lemon-Regular.ttf'),
  // "Lemon": require('./Lemon-Regular.ttf'),
}